const FETCH_START = '[news]/FETCH_START';

const FETCH_SUCCESS_NEWS_LIST = '[news]/FETCH_SUCCESS_MENU_LIST';

const FETCH_SUCCESS_DELETE_NEWS_LIST_ITEM =
  '[news]/FETCH_SUCCESS_DELETE_NEWS_LIST_ITEM';

const FETCH_ADD_SUCCESS_NEWS_LIST_ITEM =
  '[news]/FETCH_ADD_SUCCESS_NEWS_LIST_ITEM';

const FETCH_ERROR = '[news]/FETCH_ERROR';

export default {
  FETCH_START,
  FETCH_ERROR,
  FETCH_SUCCESS_NEWS_LIST,
  FETCH_ADD_SUCCESS_NEWS_LIST_ITEM,
  FETCH_SUCCESS_DELETE_NEWS_LIST_ITEM,
};
