const AUTH_REQUEST_START = '[auth]/AUTH_REQUEST_START';
const LOG_IN_REQUEST_SUCCESS = '[auth]/LOG_IN_REQUEST_SUCCESS';
const LOG_IN_REQUEST_ERROR = '[auth]/LOG_IN_REQUEST_ERROR';
const LOG_OUT_REQUEST_SUCCESS = '[auth]/LOG_OUT_REQUEST_SUCCESS';
const LOG_OUT_REQUEST_ERROR = '[auth]/LOG_OUT_REQUEST_ERROR';
const REFRESH_CURRENT_USER_START = '[auth]/REFRESH_CURRENT_USER_START';
const REFRESH_CURRENT_USER_SUCCESS = '[auth]/REFRESH_CURRENT_USER_SUCCESS';

export default {
  AUTH_REQUEST_START,
  LOG_IN_REQUEST_SUCCESS,
  LOG_IN_REQUEST_ERROR,
  LOG_OUT_REQUEST_SUCCESS,
  LOG_OUT_REQUEST_ERROR,
  REFRESH_CURRENT_USER_START,
  REFRESH_CURRENT_USER_SUCCESS,
};
