const FETCH_START = '[carousel]/FETCH_START';

const FETCH_SUCCESS_CAROUSEL_IMAGES_LIST =
  '[carousel]/FETCH_SUCCESS_CAROUSEL_IMAGES_LIST';

const FETCH_ERROR = '[carousel]/FETCH_ERROR';

const FETCHSUCCESS_CAROUSEL_IMAGE_DELETE_ITEM =
  '[carousel]/FETCHSUCCESS_CAROUSEL_IMAGE_DELETE_ITEM';

const FETCH_ADD_SUCCESS_CAROUSEL_IMAGE_ITEM =
  '[carousel]/FETCH_ADD_SUCCESS_CAROUSEL_IMAGE_ITEM';

export default {
  FETCH_START,
  FETCH_ERROR,
  FETCH_SUCCESS_CAROUSEL_IMAGES_LIST,
  FETCHSUCCESS_CAROUSEL_IMAGE_DELETE_ITEM,
  FETCH_ADD_SUCCESS_CAROUSEL_IMAGE_ITEM,
};
